### ISSUE TITLE
No Manual/Wiki

### ISSUE THREAD

**Issue by adalric** [b-man/xBoot#4]
Sorry for asking but... how am I supposed to use xboot.raspberrypi2.DEBUG.bin?

**Comment by b-man** [comment]
You'll need to rename it to kernel.bin and put it into a bootable SD card.
To interact with it you will then need to hook up a serial cable to the Raspberry Pi.

Unfortunately it isn't useful for booting Darwin quite yet. I also haven't tested the Raspberry Pi port in quite a while so I can't guarantee that it will work. Most of the recent changes done have only been verified using an emulated RealView PB-A8 in qemu.

**Comment by adalric** [comment]
Thanks! Will try it right now.
